# camera.conf - Camera Settings

WIDTH=1280
HEIGHT=720
FRAMERATE=15
EV=1
SATURATION=1
GAIN=5
CONTRAST=1
BRIGHTNESS=0.08

# --- NEW: RECORDING SETTINGS ---
REC_TOGGLE=true
REC_FREQ=30          # How often to start a recording (in seconds)
REC_DURATION=5       # How long the recording should last (in seconds)
REC_DAYS=3           # Delete files older than this many days
REC_PATH="../recordings" # Folder to save the videos